# Generated by Django 5.2.11 on 2026-02-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_carro', models.CharField(max_length=30)),
                ('preco', models.FloatField()),
                ('ano', models.IntegerField()),
                ('foto_carro', models.ImageField(upload_to='media')),
            ],
        ),
    ]
